include(
  ":example",
  ":example-shared",
  ":example-viewbinding",
  ":library",
  ":library-databinding",
  ":library-kotlin-android-extensions",
  ":library-viewbinding",
  ":example-databinding",
)
